version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: yelpcamp-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: yelpcamp-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/yelpcamp

volumes:
  mongodb_data:
